//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DunkeyDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver_Orders
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Orders Order { get; set; }
    }
}
