//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DunkeyDelivery
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DunkeyDeliveryEntities : DbContext
    {
        public DunkeyDeliveryEntities()
            : base("name=DunkeyDeliveryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Payment_Details> Payment_Details { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Order_Items> Order_Items { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Payment_Method> Payment_Method { get; set; }
        public virtual DbSet<Store_Timings> Store_Timings { get; set; }
        public virtual DbSet<Store_Rating> Store_Rating { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Driver_Orders> Driver_Orders { get; set; }
    }
}
