//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DunkeyDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Items()
        {
            this.Quantity = 0;
            this.Price = 0;
        }
    
        public int Id { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
    
        public virtual Orders Order { get; set; }
        public virtual Products Product { get; set; }
    }
}
